### ISSUE TITLE
how to record from the webcam?

### ISSUE THREAD

**Issue by sole** [mozdevs/boo#1]
MediaRecorder ? https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder

**Comment by belen-albeza** [comment]
Just drafted this http://jsfiddle.net/7zqwrsbe/

The blob format that `MediaRecorder` returns (at least by default) for video is `webM`, which Firefox can play back but not desktop video players like Quicktime. According to Maire's e-mail they should support MP4, too, but I haven't been able to get this format yet.
